#!/usr/bin/env python

import sys

"""
Bootloader Build Tool

This tool is responsible for building the bootloader from source and
copying the build outputs into the host tools directory for programming.
"""

if __name__ == '__main__':
    sys.exit(1)
